### PR TITLE
Add script deobfuscation commits to pokeyellow and label surfing minigame SFX

### PR DESCRIPTION
**Pull request by CelestialAmber**
This adds some of the deobfuscation to pokeyellow recently added to pokered, along with minor additional labelling in oakslab.asm, and labels the surfing minigame SFX.

### CODE REVIEW

**Comment by CelestialAmber** [comment]
I'm closing this pull request to reopen it with a cleaned up version of the commits.

**Comment by iimarckus** [comment]
This is good, but can you rebase to remove those duplicate commits?

**Comment by CelestialAmber** [comment]
In case you didn't see before, I managed to get rid of the duplicate commits.

**Comment by iimarckus** [comment]
All right. One more request: please rebase and squash the linebreaks commit into the previous one. (In case you don’t know how to do that: `git rebase -i HEAD^^`, then replace “pick” with “squash” on the line of the last commit.)

**Comment by rweichler** [comment]
fixed in 992d7d13ab70bfd1b9d0d4a4fb9be53c80a0114d

**Comment by rweichler** [comment]
fuck wrong repo lol

**Comment by iimarckus** [comment]
Oh, I should have said squash the linebreak removal commit into the commit that added them, not the other commit. But it doesn’t really matter.

**Pull request merged**
